site_name: sharp
site_url: https://sharp.pixelplumbing.com/
repo_url: https://github.com/lovell/sharp
site_description: High performance Node.js image processing, the fastest module to resize JPEG, PNG, WebP and TIFF images
copyright: <a href="https://pixelplumbing.com/">pixelplumbing.com</a>
google_analytics: ['UA-13034748-12', 'sharp.pixelplumbing.com']
theme: readthedocs
extra_css:
  - css/extra.css
markdown_extensions:
  - toc:
      permalink: True
pages:
  - Home: index.md
  - Installation: install.md
  - API:
    - Constructor: api-constructor.md
    - Input: api-input.md
    - Output: api-output.md
    - "Resizing images": api-resize.md
    - "Compositing images": api-composite.md
    - "Image operations": api-operation.md
    - "Colour manipulation": api-colour.md
    - "Channel manipulation": api-channel.md
    - Utilities: api-utility.md
  - Performance: performance.md
  - Changelog: changelog.md
